name: Website Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Step 1: Checkout repository
        - name: Checkout repository
          uses: actions/checkout@v2

        # Step 2: Install Hugo Extended Version (for SCSS support)
        - name: Install Hugo Extended Version
          run: |
            wget https://github.com/gohugoio/hugo/releases/download/v0.147.0/hugo_extended_withdeploy_0.147.0_linux-amd64.deb
            sudo dpkg -i hugo_extended_withdeploy_0.147.0_linux-amd64.deb

        # Step 3: Build the site with Hugo
        - name: Build the site with Hugo
          run: hugo

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public